# Generated by Django 2.1.2 on 2019-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advc_descript', models.CharField(blank=True, max_length=50, null=True)),
                ('advc_durations', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvDataSynch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advd_type', models.SmallIntegerField(choices=[(0, 'Relex'), (1, 'Advertise')], default=0)),
                ('advd_value', models.TextField(blank=True, null=True)),
                ('advd_error', models.BooleanField(default=False)),
                ('advd_synchronized', models.BooleanField(default=False)),
                ('advd_description', models.CharField(blank=True, max_length=100, null=True)),
                ('advd_request_remove', models.BooleanField(default=False)),
                ('advd_durations', models.CharField(default='[]', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdvPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advp_name', models.CharField(max_length=50)),
                ('advp_durations', models.SmallIntegerField(default=0)),
                ('advp_interval', models.SmallIntegerField(default=1)),
                ('advp_timestart', models.TimeField(blank=True, null=True)),
                ('advp_timeend', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('advs_name', models.CharField(max_length=50)),
                ('advs_type', models.SmallIntegerField(choices=[(0, 'Relex'), (1, 'Advertise')], default=0)),
                ('advs_datetart', models.DateField(blank=True, null=True)),
                ('advs_dateend', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneNetContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('onc_priority', models.SmallIntegerField(choices=[(1, 'Flexible'), (2, 'Rigit')], default=1)),
                ('onc_content_id', models.CharField(blank=True, max_length=100)),
                ('onc_content', models.TextField(blank=True, null=True)),
                ('onc_duration', models.SmallIntegerField(default=5)),
                ('onc_timestart', models.DateTimeField()),
                ('onc_interval', models.SmallIntegerField(default=1)),
                ('onc_timeout', models.SmallIntegerField(default=10)),
                ('onc_delay', models.SmallIntegerField(default=5)),
                ('onc_sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
