# Generated by Django 2.1.2 on 2019-01-30 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adversiting', '0001_initial'),
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onenetcontent',
            name='create_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_adversiting_onenetcontent_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='onenetcontent',
            name='onc_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onenetcontent', to='device.Device'),
        ),
        migrations.AddField(
            model_name='onenetcontent',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_adversiting_onenetcontent_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advschedule',
            name='advs_devices',
            field=models.ManyToManyField(related_name='advschedule', to='device.Device'),
        ),
        migrations.AddField(
            model_name='advschedule',
            name='create_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_adversiting_advschedule_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advschedule',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_adversiting_advschedule_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advplan',
            name='advp_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advplan', to='adversiting.AdvSchedule'),
        ),
        migrations.AddField(
            model_name='advplan',
            name='create_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_adversiting_advplan_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advplan',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_adversiting_advplan_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advdatasynch',
            name='advd_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advsync', to='device.Device'),
        ),
        migrations.AddField(
            model_name='advdatasynch',
            name='create_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_adversiting_advdatasynch_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advdatasynch',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_adversiting_advdatasynch_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advcontent',
            name='advc_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advcontent', to='media.Media'),
        ),
        migrations.AddField(
            model_name='advcontent',
            name='advc_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advcontent', to='adversiting.AdvPlan'),
        ),
        migrations.AddField(
            model_name='advcontent',
            name='advc_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advcontent', to='adversiting.AdvSchedule'),
        ),
        migrations.AddField(
            model_name='advcontent',
            name='create_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_adversiting_advcontent_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advcontent',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_adversiting_advcontent_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='advdatasynch',
            unique_together={('advd_device', 'advd_type')},
        ),
    ]
