# Generated by Django 2.1.2 on 2019-07-22 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
        ('globalconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('poi_items', models.TextField(default='[]')),
                ('poi_data_id', models.PositiveIntegerField()),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_positioncontrol_positionitem_related', to=settings.AUTH_USER_MODEL)),
                ('poi_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_items', to='media.Media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PositionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pov_view_id', models.CharField(choices=[('VIEW_ADV', 'VIEW_ADV'), ('VIEW_LIGHTING', 'VIEW_LIGHTING'), ('VIEW_ACC', 'VIEW_ACC')], max_length=20)),
                ('pov_data_object', models.CharField(choices=[('FLOOR', 'OBJECT_FLOOR')], max_length=20)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_positioncontrol_positionview_related', to=settings.AUTH_USER_MODEL)),
                ('pov_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='globalconfig.Building')),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_positioncontrol_positionview_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='positionitem',
            name='poi_pos_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_items', to='positioncontrol.PositionView'),
        ),
        migrations.AddField(
            model_name='positionitem',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_positioncontrol_positionitem_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='positionview',
            unique_together={('pov_building', 'pov_view_id')},
        ),
    ]
