# Generated by Django 2.1.2 on 2019-07-22 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dev_diskspace',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='dev_mediaplay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.Media'),
        ),
        migrations.AddField(
            model_name='device',
            name='dev_software_version',
            field=models.CharField(blank=True, default='0.0.0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='dev_sync_state',
            field=models.SmallIntegerField(choices=[(0, 'Done'), (1, 'Failed'), (2, 'Waiting')], default=0),
        ),
    ]
