# Generated by Django 2.1.2 on 2019-01-30 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bdg_name', models.CharField(max_length=50)),
                ('bdg_address', models.CharField(max_length=100)),
                ('bdg_description', models.CharField(max_length=100)),
                ('bdg_rest_day', models.TextField(blank=True, null=True)),
                ('bdg_holiday', models.TextField(blank=True, null=True)),
                ('bdg_synchronized', models.BooleanField(default=True)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_globalconfig_building_related', to=settings.AUTH_USER_MODEL)),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_globalconfig_building_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('door_name', models.CharField(max_length=50)),
                ('door_description', models.CharField(blank=True, max_length=100, null=True)),
                ('door_position', models.SmallIntegerField(blank=True, null=True)),
                ('door_state', models.SmallIntegerField(choices=[(1, 'Closed'), (0, 'Opened')], default=1)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_globalconfig_door_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flr_code', models.CharField(max_length=50)),
                ('flr_name', models.CharField(max_length=50)),
                ('flr_state', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1)),
                ('flr_position', models.SmallIntegerField(default=1)),
                ('flr_is_default', models.BooleanField(default=False)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_globalconfig_floor_related', to=settings.AUTH_USER_MODEL)),
                ('flr_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='globalconfig.Building')),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_globalconfig_floor_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('zone_code', models.CharField(max_length=50)),
                ('zone_name', models.CharField(max_length=50)),
                ('zone_position', models.SmallIntegerField(blank=True, null=True)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_globalconfig_zone_related', to=settings.AUTH_USER_MODEL)),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_globalconfig_zone_related', to=settings.AUTH_USER_MODEL)),
                ('zone_floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='globalconfig.Floor')),
            ],
            options={
                'ordering': ['zone_floor__flr_building', 'zone_floor'],
            },
        ),
        migrations.AddField(
            model_name='door',
            name='door_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='globalconfig.Zone'),
        ),
        migrations.AddField(
            model_name='door',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_globalconfig_door_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('flr_building', 'flr_position')},
        ),
    ]
