# Generated by Django 2.1.2 on 2019-01-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfg_key', models.CharField(max_length=255, unique=True)),
                ('cfg_value', models.TextField()),
                ('cfg_note', models.TextField()),
            ],
            options={
                'db_table': 'TblF9SystemConfig',
            },
        ),
    ]
