# Generated by Django 2.1.2 on 2019-01-30 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('med_name', models.CharField(max_length=50)),
                ('med_real_name', models.CharField(blank=True, max_length=50, null=True)),
                ('med_type', models.CharField(blank=True, max_length=15, null=True)),
                ('med_content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('med_size', models.IntegerField(blank=True, null=True)),
                ('med_path', models.CharField(blank=True, max_length=200, null=True)),
                ('med_url', models.CharField(blank=True, max_length=100, null=True)),
                ('med_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('med_md5checksum', models.CharField(blank=True, max_length=50, null=True)),
                ('med_description', models.CharField(blank=True, max_length=200, null=True)),
                ('med_start_date', models.DateField(blank=True, null=True)),
                ('med_end_date', models.DateField(blank=True, null=True)),
                ('med_duration', models.IntegerField(blank=True, null=True)),
                ('med_youtube_id', models.CharField(blank=True, max_length=20, null=True)),
                ('med_is_folder', models.BooleanField(default=False)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_media_media_related', to=settings.AUTH_USER_MODEL)),
                ('med_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='media.Media')),
                ('med_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_media_media_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
