# Generated by Django 2.1.2 on 2019-07-22 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cgp_name', models.CharField(max_length=50)),
                ('cgp_code', models.CharField(max_length=50, unique=True)),
                ('cgp_users', models.ManyToManyField(blank=True, related_name='channelgroup', to=settings.AUTH_USER_MODEL)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_notify_channelgroup_related', to=settings.AUTH_USER_MODEL)),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_notify_channelgroup_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ntf_name', models.CharField(max_length=50, unique=True)),
                ('ntf_type', models.CharField(choices=[('success', 'Success'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=15)),
                ('ntf_level', models.SmallIntegerField(choices=[(0, 'Normal'), (1, 'Medium'), (2, 'Gravity'), (3, 'Dangerous')], default=0)),
                ('ntf_message', models.TextField(max_length=3000)),
                ('ntf_message_html', models.TextField()),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_notify_notify_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uny_viewed', models.BooleanField(default=False)),
                ('create_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_notify_usernotify_related', to=settings.AUTH_USER_MODEL)),
                ('uny_notify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernotify', to='notify.Notify')),
                ('uny_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernotify', to=settings.AUTH_USER_MODEL)),
                ('update_uid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_notify_usernotify_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notify',
            name='ntf_users',
            field=models.ManyToManyField(blank=True, related_name='notify', through='notify.UserNotify', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notify',
            name='update_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_notify_notify_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usernotify',
            unique_together={('uny_user', 'uny_notify')},
        ),
    ]
